### ISSUE TITLE
TypeError: get_hash() missing 1 required positional argument: 'use_fast_tokenizer'

### ISSUE THREAD

**Issue by puraminy** [HKUNLP/UnifiedSKG#17]
I generated some predictions for `fetaqa` task. Then I tried to run its evaluator on the output results (predictions_predict.json). I get the following error for bertscore metric.

```
File "/home/pouramini/anaconda3/envs/uni/lib/python3.7/site-packages/datasets/metric.py", line 402, in compute
    output = self._compute(predictions=predictions, references=references, **kwargs)
  File "/home/pouramini/.cache/huggingface/modules/datasets_modules/metrics/bertscore/ad3c901af4d4f2c58af08db5c6aae5af2a3668edcf7c8f3fa9419c22807ad482/bertscore.py", line 147, in _compute
    use_custom_baseline=baseline_path is not None,
TypeError: get_hash() missing 1 required positional argument: 'use_fast_tokenizer'

```

There could be a mismatch between datasets metrics and bertscore, however I tried to install the versions in yaml.

**Comment by Timothyxxx** [comment]
Hi,

Did you build dependencies as shown in [here](https://github.com/HKUNLP/UnifiedSKG#dependencies)?
It seems a problem caused by huggingface-datasets version.

Hope these information helpful!

Thanks!

**Comment by puraminy** [comment]
Yes, you didn't specified any version for `datasets` in the yaml file. Mine is `1.11.0`.  The bert-score version you specified is `0.3.10` however.

Which version should be used?

**Comment by Timothyxxx** [comment]
Oh I see the problem.
Actually we didn't specify the version in yaml file because we want to avoid conflict during `conda env create -f py3.7pytorch1.8.yaml`(there are so many metrics, datasets and reliance...), and after that command is finished, you need to run `pip install datasets==1.14.0` specially to install the `datasets v 1.14.0` as we [used](https://github.com/HKUNLP/UnifiedSKG#dependencies).
Please try that and see if it can solve your problem.

Thanks!

**Comment by puraminy** [comment]
Thanks, before reading your comment I tried datasets `1.18.3` and the problem was resolved, I will try the version you said

**Comment by Timothyxxx** [comment]
Okay, feel free to re-open this if you encounter further problem in the future.
