### ISSUE TITLE
About training time

### ISSUE THREAD

**Issue by LucyFann** [HKUNLP/UnifiedSKG#33]
Hi, first of all, thanks for your brilliant work! I try to add a new task into UnifiedSKG(similar with kvret, but much bigger) using prefix tuning for t5-based. However, the training time is so long. I use one GPU3090, bsz=4. One epoch takes about 2.5 hours, could you give me any advice? In table 18 in UnifiedSKG, "Preﬁx-tuning needs more steps to converge and converges to comparable performances". Does this mean that prefix-tuning needs more training time to achieve the same effect as finetune? 
Thanks a lot! Lucy

**Comment by Timothyxxx** [comment]
Hi,

Thanks for your question!
I think 2.5h an epoch for one 3090 make sense. I guess it may due to the fact that your training set contains a lot of examples.(the whole training needs fewer epochs to converge as a result). I recommend you try to finetune T5-base directly for comparison. The time spent in one epoch each should be approximate the same for checking.

Hope these information useful!
Tianbao

**Comment by LucyFann** [comment]
Thanks for your quick reply! I will try this!
