### ISSUE TITLE
Model checkpoints and outputs for T5-3b

### ISSUE THREAD

**Issue by carlos-gemmell** [HKUNLP/UnifiedSKG#37]
Hi, thank you for the cool work!

I am a student at the University of Glasgow looking to reproduce your results for tabular question answering.
The largest checkpoints available to download are T5 large yet to make the best analysis we require T5 3B. 

May you upload these to the hugging face model hub please?

Alternatively, could you provide model predictions for all datasets and model variants for test and dev sets since then the models themselves will not need to be run.

Thanks!

**Comment by Timothyxxx** [comment]
Hi,

Thanks for your question and sorry for the delay! Unfortunately, the model weights at that time have been cleaned. For replication, you can refer to issue #14 for details of running. And if you don't want to train yourself and just need the weight, you can also refer to [PICARD](https://github.com/ServiceNow/picard) for its uploaded weight, since we got similar formulation and closed results.
Feel free to contact us if you have further questions!

Thanks!
