### ISSUE TITLE
Hyperparameters for all the datasets

### ISSUE THREAD

**Issue by gao-xiao-bai** [HKUNLP/UnifiedSKG#8]
It seems that you only report the detailed hyperparameters for WikiTQ. Where can we find the hyperparameters for other datasets that can reproduce the results?

**Comment by Timothyxxx** [comment]
Hi Chang,

Thanks for double-checking!  Actually, we provided all the hyper-parameters for all 21 tasks in the Table 17 _Hyperparameters for each SKG task_ of our [paper](https://arxiv.org/pdf/2201.05966.pdf). Sorry we have to place that to Appendix due to limited space in main body. Free free to contact us again if you have any difficulties in re-producing the results or using this framework. Hope this information is helpful!

Thanks

**Comment by gao-xiao-bai** [comment]
OK. Thank you for your quick response.
